// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97AIZmRNOlrPqEYQ9xDP4MLnhBQtz1Ns',
    appId: '1:997614266269:web:dd47d5c4e683a3d5637174',
    messagingSenderId: '997614266269',
    projectId: 'bootcamp-8414b',
    authDomain: 'bootcamp-8414b.firebaseapp.com',
    storageBucket: 'bootcamp-8414b.firebasestorage.app',
    measurementId: 'G-RLJLMJ9630',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D6e7IVEJsMbjYMxc7--7mPx0y8A9IZM',
    appId: '1:997614266269:android:0222c3e1a7cb0d80637174',
    messagingSenderId: '997614266269',
    projectId: 'bootcamp-8414b',
    storageBucket: 'bootcamp-8414b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqeD71McWuiwu3GElpBwWs6znjgACc04',
    appId: '1:997614266269:ios:b8c950c23b333eeb637174',
    messagingSenderId: '997614266269',
    projectId: 'bootcamp-8414b',
    storageBucket: 'bootcamp-8414b.firebasestorage.app',
    iosBundleId: 'com.example.zBootcamp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqeD71McWuiwu3GElpBwWs6znjgACc04',
    appId: '1:997614266269:ios:b8c950c23b333eeb637174',
    messagingSenderId: '997614266269',
    projectId: 'bootcamp-8414b',
    storageBucket: 'bootcamp-8414b.firebasestorage.app',
    iosBundleId: 'com.example.zBootcamp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC97AIZmRNOlrPqEYQ9xDP4MLnhBQtz1Ns',
    appId: '1:997614266269:web:54611e1b70bcddc6637174',
    messagingSenderId: '997614266269',
    projectId: 'bootcamp-8414b',
    authDomain: 'bootcamp-8414b.firebaseapp.com',
    storageBucket: 'bootcamp-8414b.firebasestorage.app',
    measurementId: 'G-ZZ5WFLBSQE',
  );
}
